#include<stdio.h>

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * */


void usage(char *this_ex){
    printf("Project Euler Problem #2:\n");
    printf("Find the sum of all the even Fibonacci numbers below N\n");
    printf("Pass N in via the command line as follows:\n");
    printf("%s <N>\n", this_ex);   
}


//This takes 1.7 seconds for n = 400000000
unsigned long long naive_sol(n){
    int first = 0;
    int temp = 0;
    int second = 1;
    unsigned long long sum = 0;

    while(second < n){
        temp = second;
        second = first + second;
        first = temp;
        //printf("First: %d, Second: %d, Sum: %d\n", first, second, sum);
        if(second % 2 ==0) sum += second;
    }
    return sum;
}        

int main(int argc, char **argv){
    if(argc != 2){
        usage(argv[0]);
        return -1;
    }
    unsigned int n = atoi(argv[1]);
    printf("N is %d\n", n);

    if(n < 1){
        printf("Please use a value of n between 1 and 4,294,967,296.\n");
        return -1;
    }
    //printf("The sum is %lld\n", naive_sol(n));
    printf("The sum is %lld\n", naive_sol(n));

    return 0;
}

